// my-vue-pwa/src/components/AdminView.vue
<template>
    <div class="admin-view">
      <h2>Survey Submissions</h2>
      <table>
        <thead>
          <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Email</th>
            <th>Response</th>
            <th>Comments</th>
            <th>Date</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="submission in submissions" :key="submission.id">
            <td>{{ submission.id }}</td>
            <td>{{ submission.name }}</td>
            <td>{{ submission.email }}</td>
            <td>{{ submission.question1 }}</td>
            <td>{{ submission.comments }}</td>
            <td>{{ submission.date }}</td>
          </tr>
        </tbody>
      </table>
    </div>
  </template>
  
  <script>
  import axios from 'axios';
  
  export default {
    name: 'AdminView',
    data() {
      return {
        submissions: []
      };
    },
    created() {
      this.fetchData();
    },
    methods: {
      async fetchData() {
        try {
          // Uncomment and update this when using a real API endpoint:
          // const response = await axios.get('https://your-api-endpoint/submissions');
          // this.submissions = response.data;
  
          // Temporarily using the local JSON file instead:
          const response = await fetch('/submissions.json');
          if (response.ok) {
            this.submissions = await response.json();
          } else {
            console.error('Failed to fetch data from local JSON file.');
          }
        } catch (error) {
          console.error('Error fetching survey submissions:', error);
        }
      }
    }
  };
  </script>
  
  <style scoped>
  .admin-view {
    margin: 2rem auto;
    max-width: 800px;
  }
  
  table {
    width: 100%;
    border-collapse: collapse;
    margin-top: 1rem;
  }
  
  th, td {
    border: 1px solid #ddd;
    padding: 0.75rem;
    text-align: left;
  }
  
  th {
    background-color: #f0f0f0;
  }
  
  tr:nth-child(even) {
    background-color: #f9f9f9;
  }
  </style>

// my-react-pwa/src/components/AdminView.jsx
import React, { useState, useEffect } from "react";
import "../App.css"; 

function AdminView() {
  const [submissions, setSubmissions] = useState([]);
  const [error, setError] = useState(null);

  useEffect(() => {
    fetchSubmissions();
  }, []);

  const fetchSubmissions = async () => {
    try {
      // Fetch data from the local JSON file or API if it was available...
      const response = await fetch("/submissions.json");
      if (!response.ok) {
        throw new Error("Failed to fetch data from local JSON file.");
      }
      const data = await response.json();
      setSubmissions(data);
    } catch (err) {
      console.error("Error fetching survey submissions:", err);
      setError(err.message);
    }
  };

  return (
    <div className="admin-view">
      <h2>Survey Submissions</h2>
      {error && <p className="error-message">{error}</p>}
      <table>
        <thead>
          <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Email</th>
            <th>Response</th>
            <th>Comments</th>
            <th>Date</th>
          </tr>
        </thead>
        <tbody>
          {submissions.map((submission) => (
            <tr key={submission.id}>
              <td>{submission.id}</td>
              <td>{submission.name}</td>
              <td>{submission.email}</td>
              <td>{submission.question1}</td>
              <td>{submission.comments}</td>
              <td>{submission.date}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

export default AdminView;
